kind: ServiceInstance
apiVersion: steward.deis.io/v1
metadata:
  name: "{{.Values.InstanceName}}"
  namespace: {{.Release.Namespace}}
  labels:
    type: instance
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": "{{.Release.Time.Seconds}}"
spec:
  id: {{ uuidv4 }}
  service_class_ref:
    kind: ServiceClass
    namespace: {{.Values.ServiceClassNamespace}}
    name: "{{.Values.BrokerName}}-{{.Values.ServiceName}}"
  plan_id: {{.Values.PlanId}}
status:
