kind: ServiceBinding
apiVersion: steward.deis.io/v1
metadata:
  name: "{{.Values.BindingName}}"
  namespace: {{.Release.Namespace}}
  labels:
    type: binding
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": "{{.Release.Time.Seconds}}"
spec:
    id: {{ uuidv4 }}
    service_instance_ref:
      kind: Instance
      namespace: {{.Release.Namespace}}
      name: "{{.Values.InstanceName}}"
    parameters:
    secret_name: {{.Values.SecretName}}
status:
