# Default values for sample-cf-broker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Name: cf-sample-broker
ServicePort: 80
ContainerPort: 8080
Component: "cf-sample-broker"
Replicas: 1
Image: "quay.io/deisci/cf-sample-broker"
ImageTag: "devel"
ImagePullPolicy: "Always"
