kind: ServiceInstance
apiVersion: steward.deis.io/v1
metadata:
  name: my-s3-bucket
  namespace: default
spec:
  id: #instance-uuid#
  service_class_ref:
    kind: ServiceClass
    namespace: steward
    name: s3-broker-bucket
  plan_id: eaad05d8-2e01-11e5-9184-feff819cdc9f
