# Default values for s3-service-provider.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

ServicePort: 80
ContainerPort: 8080
Component: "steward"
Replicas: 1
StewardImage: "quay.io/arschles/steward-cf"
StewardImageTag: "devel"
StewardImagePullPolicy: "Always"
StewardWatchNamespaces: "default,steward"

BrokerImage: "lachlanevenson/s3-broker"
BrokerImageTag: "latest"
BrokerImagePullPolicy: "Always"
CfBrokerScheme: "http"
CfBrokerPort: 3000
CfBrokerUsername: "username"
CfBrokerPassword: "password"

CfBrokerServiceId: "98FF26D0-2E01-11E5-9184-FEFF819CDC9F"
CfBrokerServiceName: "demo-service"
CfBrokerPlanId: "EAAD05D8-2E01-11E5-9184-FEFF819CDC9F"
CfBrokerPlanName: "demo-plan"

AdminAwsAccessKeyId: ""
AdminAwsSecretAccessKey: ""
