kind: Binding
apiVersion: steward.deis.io/v1
metadata:
  name: "{{.Values.InstanceName}}"
  namespace: {{.Release.Namespace}}
  labels:
    type: broker
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": "{{.Release.Time.Seconds}}"
spec:
    id: {{ uuidv4 }}
    instance_ref:
      kind: Instance
      namespace: {{.Release.Namespace}}
      name: "{{.Values.InstanceName}}"
    parameters:
    secret_name: {{.Values.SecretName}}
status:
