apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-s3-broker-creds"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-s3-broker"
data:
  aws-access-key-id: {{ default "" .Values.AdminAwsAccessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ default "" .Values.AdminAwsSecretAccessKey | b64enc | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-s3-broker"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-s3-broker"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
  - port: {{.Values.Port}}
    targetPort: {{.Values.Port}}
  selector:
    component: "{{.Release.Name}}-s3-broker"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-s3-broker"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-s3-broker"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{ .Values.Replicas }}
  template:
    metadata:
      name: "{{ printf "%s-s3-broker" .Release.Name | trunc 24 }}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-s3-broker"
      annotations:
        "helm.sh/created": {{.Release.Time.Seconds | quote }}
    spec:
      containers:
      - name: "{{ printf "%s-s3-broker" .Release.Name | trunc 24 }}"
        image: "{{.Values.Image}}:{{.Values.ImageTag}}"
        imagePullPolicy: "{{.Values.ImagePullPolicy}}"
        command: ["/s3-broker", "--config=/config/s3-broker-config.json"]
        volumeMounts:
        - mountPath: /config
          name: config-volume
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-s3-broker-creds"
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-s3-broker-creds"
              key: aws-secret-access-key
      volumes:
        - name: config-volume
          configMap:
            name: "{{ .Release.Name }}-s3-broker-config"
