kind: ServiceBroker
apiVersion: steward.deis.io/v1
metadata:
  name: {{.Values.BrokerName}}
  namespace: {{.Release.Namespace}}
  labels:
    type: broker
    release: {{.Release.Name | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    component: {{.Release.Name}}-{{.Values.Component}}
  annotations:
    "helm.sh/created": "{{.Release.Time.Seconds }}"
spec:
  url: "{{.Values.AccessScheme}}://{{.Values.BrokerReleaseName}}-s3-broker.{{.Release.Namespace}}.svc.cluster.local:{{.Values.BrokerPort}}"
  username: {{.Values.BrokerUsername}}
  password: {{.Values.BrokerPassword}}
status:
