kind: Instance
apiVersion: steward.deis.io/v1
metadata:
  name: "{{.Values.InstanceName}}"
  namespace: {{.Release.Namespace}}
  labels:
    type: broker
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": "{{.Release.Time.Seconds}}"
spec:
  id: 09e13f8c-8dee-480d-9e29-896ae12534fa
  service_class_ref:
    kind: ServiceClass
    namespace: {{.Values.ServiceClassNamespace}}
    name: "{{.Values.BrokerName}}-{{.Values.ServiceName}}"
  plan_id: {{.Values.S3PlanID}}
status:
